id: a7287406aa744e5682116058cf3e98fe
initial_creation_type: ocr
source_metadata:
  volumes:
    7b81a06cb00847019b9164c9a72fd0d0:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
